pub mod autotune_menu;
#[cfg(target_os = "windows")]
pub mod defender_menu;
pub mod download_menu;
pub mod download_submenu;
pub mod fakes_menu;
pub mod gamefilter_menu;
pub mod lists_menu;
pub mod main_menu;
pub mod service_menu;
pub mod strategy_menu;
pub mod tag_menu;
