use std::fs;
use std::path::Path;

fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .filter(|p| !p.is_empty())
        .map(|p| {
            let mut chars = p.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().to_string() + chars.as_str(),
            }
        })
        .collect()
}

fn main() {
    let backends_dir = Path::new("src/firewalls/backends");
    let dest = backends_dir.join("_backends.rs");

    let mut backends = Vec::new();

    if let Ok(entries) = fs::read_dir(backends_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().and_then(|s| s.to_str()) == Some("rs") {
                if let Some(stem) = path.file_stem().and_then(|s| s.to_str()) {
                    if stem != "mod" && !stem.starts_with('_') {
                        backends.push(stem.to_string());
                    }
                }
            }
        }
    }

    backends.sort_by(|a, b| {
        if a == "nftables" {
            std::cmp::Ordering::Less
        } else if b == "nftables" {
            std::cmp::Ordering::Greater
        } else {
            a.cmp(b)
        }
    });

    let mut output = String::new();
    output.push_str("// Auto-generated by build.rs - DO NOT EDIT\n\n");

    for backend in &backends {
        output.push_str(&format!("pub mod {};\n", backend));
    }

    output.push_str("\ndefine_backends! {\n");
    for backend in &backends {
        let variant = to_pascal_case(backend);
        output.push_str(&format!(
            "    {} => {}: {}Backend as \"backend_{}\",\n",
            variant, backend, variant, backend
        ));
    }
    output.push_str("}\n");

    fs::write(&dest, output).unwrap();

    println!("cargo:rerun-if-changed=src/firewalls/backends/");
}
