name: Lint PR Title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

concurrency:
  group: lint-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: none
  actions: none
  pull-requests: read
  statuses: write

jobs:
  validate-pr:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
